spring:
  application:
    name: People Search
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    password: password
    username: sa
  h2:
    console:
      enabled: false

application:
  heroku-url: https://bpdts-test-app.herokuapp.com

springdoc:
  swagger-ui:
    path: /